name: Run Extractor

on:
  workflow_dispatch:
    inputs:
      apimName:
        description: "Nom de l'instance APIM"
        required: true
      resourceGroup:
        description: "Nom du groupe de ressources"
        required: true
      outputFolder:
        description: "Répertoire de sortie"
        required: false
        default: "extracted-apis"

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install APIOps Extractor
      run: |
        dotnet tool install --global Microsoft.Azure.ApiManagement.ArmTemplates.Extractor.Tool

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Extractor
      run: |
        extractor \
          --sourceApimName "${{ github.event.inputs.apimName }}" \
          --resourceGroup "${{ github.event.inputs.resourceGroup }}" \
          --fileFolder "${{ github.event.inputs.outputFolder }}"
