name: Run Extractor

on:
  workflow_dispatch:
    inputs:
      apimName:
        description: "Nom de l'instance APIM"
        required: true
      resourceGroup:
        description: "Nom du resource group Azure"
        required: true
      outputFolder:
        description: "Répertoire de sortie"
        required: false
        default: "extracted"

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download APIOps Extractor Binary
      run: |
        curl -L -o extractor.zip https://aka.ms/apimextractor-linux
        unzip extractor.zip -d extractor
        chmod +x extractor/Extractor

    - name: Run Extractor
      run: |
        ./extractor/Extractor \
          --sourceApimName "${{ github.event.inputs.apimName }}" \
          --resourceGroup "${{ github.event.inputs.resourceGroup }}" \
          --fileFolder "${{ github.event.inputs.outputFolder }}"
